[workspace]
members = ["engine", "hext-boards", "cli"]

resolver = "2"

[workspace.package]
license = "GPL-3.0-or-later"
authors = ["Odilf <odysseas.maheras@gmail.com>"]
description = "Hexagonal chess"
homepage = "https://chessagon.odilf.com"
