[package]
name = "chessagon-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
chessagon-core = { path = "../core" }

[lints]
workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
