[package]
name = "chessagon-core"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra.workspace = true
thiserror.workspace = true
strum.workspace = true
tracing.workspace = true
hext-boards.workspace = true 
gcd = "2.3.0"

[dev-dependencies]
pretty_assertions.workspace = true
