[package]
name = "chessagon-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra.workspace = true
thiserror.workspace = true
strum.workspace = true

[dev-dependencies]
hext-boards.workspace = true 
pretty_assertions = "1.4.1"
